# Generated by Django 5.2.12 on 2026-03-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                ("comp_id", models.AutoField(primary_key=True, serialize=False)),
                ("comp_name", models.CharField(max_length=255)),
                ("comp_url", models.URLField()),
                ("comp_date", models.DateField()),
            ],
            options={
                "unique_together": {("comp_name", "comp_date")},
            },
        ),
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("athlete_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "MALE"), ("female", "FEMALE")], max_length=6
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("team", models.CharField(blank=True, max_length=100)),
                ("session", models.CharField(blank=True, max_length=100)),
                ("flight", models.CharField(blank=True, max_length=100)),
                ("division", models.CharField(blank=True, max_length=100)),
                ("bw", models.FloatField(blank=True, null=True)),
                ("weight_class", models.CharField(blank=True, max_length=50)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("best_squat", models.IntegerField(default=0)),
                ("best_bench", models.IntegerField(default=0)),
                ("best_dead", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                ("points", models.FloatField(blank=True, null=True)),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athletes",
                        to="ironCrawler.competition",
                    ),
                ),
            ],
        ),
    ]
