# Generated by Django 5.2.12 on 2026-03-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ironCrawler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="athlete",
            name="best_bench",
        ),
        migrations.RemoveField(
            model_name="athlete",
            name="best_dead",
        ),
        migrations.RemoveField(
            model_name="athlete",
            name="best_squat",
        ),
        migrations.RemoveField(
            model_name="athlete",
            name="bw",
        ),
        migrations.RemoveField(
            model_name="athlete",
            name="flight",
        ),
        migrations.RemoveField(
            model_name="athlete",
            name="points",
        ),
        migrations.RemoveField(
            model_name="athlete",
            name="session",
        ),
        migrations.RemoveField(
            model_name="athlete",
            name="total",
        ),
        migrations.AlterField(
            model_name="athlete",
            name="athlete_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("raw", "Raw"), ("equipped", "Equipped")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="division",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("boy", "Boy"),
                    ("girl", "Girl"),
                    ("boys", "Boys"),
                    ("girls", "Girls"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="team",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="weight_class",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
