# Generated by Django 6.0.6 on 2026-06-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironCrawler', '0002_remove_athlete_best_bench_remove_athlete_best_dead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='best_bench',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='best_deadlift',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='best_squat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='body_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='dots_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
